In [1]:
import numpy as np
import pandas as pd

In [2]:
data_west = pd.read_excel("West_Bengal_filter.xlsx",sheet_name="Sheet1")
data_telangana = pd.read_excel("Telangana_filter.xlsx",sheet_name="Sheet1")
data_tamil = pd.read_excel("Tamil_Nadu_filter.xlsx",sheet_name="Sheet1")
data_rajasthan = pd.read_excel("Rajasthan_filter.xlsx",sheet_name="Sheet1")
data_andhra = pd.read_excel("Andhra_Pradesh_filter.xlsx",sheet_name="Sheet1")

In [3]:
final_data = pd.concat([data_andhra,data_rajasthan,data_tamil,data_telangana,data_west], axis=0)

In [4]:
final_data.head()

PH      EC  TOT_ALKALINITY    CA     MG     NA  BICARBONATE  FLUORIDE
0  7.83  2000.0          314.75  66.0  70.59  250.0        384.0      2.20
1  7.61   674.0             NaN   NaN    NaN    NaN          NaN      1.20
2  8.17   786.0          240.16  24.0  24.34  106.0        293.0      3.83
3   7.6   990.0          440.16  24.0  25.56  180.0        537.0      3.80
4  7.64   862.0          235.25  62.0  20.74   81.0        287.0      2.10

In [5]:
final_data.count()

PH                20977
EC                21010
TOT_ALKALINITY    14653
CA                19681
MG                19679
NA                19575
BICARBONATE       19840
FLUORIDE          20391
dtype: int64

In [6]:
final_data = final_data.dropna(axis=0)
final_data.count()

PH                14317
EC                14317
TOT_ALKALINITY    14317
CA                14317
MG                14317
NA                14317
BICARBONATE       14317
FLUORIDE          14317
dtype: int64

In [7]:
final_data = final_data.astype(float)
final_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14317 entries, 0 to 4031
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   PH              14317 non-null  float64
 1   EC              14317 non-null  float64
 2   TOT_ALKALINITY  14317 non-null  float64
 3   CA              14317 non-null  float64
 4   MG              14317 non-null  float64
 5   NA              14317 non-null  float64
 6   BICARBONATE     14317 non-null  float64
 7   FLUORIDE        14317 non-null  float64
dtypes: float64(8)
memory usage: 1006.7 KB


In [8]:
final_data.corr()

PH        EC  TOT_ALKALINITY        CA        MG  \
PH              1.000000  0.007638        0.159336 -0.258240 -0.072663   
EC              0.007638  1.000000        0.326843  0.588173  0.419715   
TOT_ALKALINITY  0.159336  0.326843        1.000000  0.066551  0.037629   
CA             -0.258240  0.588173        0.066551  1.000000  0.335212   
MG             -0.072663  0.419715        0.037629  0.335212  1.000000   
NA              0.111236  0.893397        0.365656  0.431942  0.316331   
BICARBONATE     0.004120  0.376564        0.858184  0.134535  0.158502   
FLUORIDE        0.104397  0.144962        0.207236 -0.021407  0.032624   

                      NA  BICARBONATE  FLUORIDE  
PH              0.111236     0.004120  0.104397  
EC              0.893397     0.376564  0.144962  
TOT_ALKALINITY  0.365656     0.858184  0.207236  
CA              0.431942     0.134535 -0.021407  
MG              0.316331     0.158502  0.032624  
NA              1.000000     0.383354  0.205203  
BICARBONATE     0.383354     1.000000  0.219009  
FLUORIDE        0.205203     0.219009  1.000000

In [9]:
final_data['Bin_Fluoride'] = np.where( final_data['FLUORIDE'] >= 1,1,0)
final_data['Bin_Fluoride'].value_counts()

0    9685
1    4632
Name: Bin_Fluoride, dtype: int64

In [10]:
final_data.head()

PH      EC  TOT_ALKALINITY    CA     MG     NA  BICARBONATE  FLUORIDE  \
0  7.83  2000.0          314.75  66.0  70.59  250.0        384.0      2.20   
2  8.17   786.0          240.16  24.0  24.34  106.0        293.0      3.83   
3  7.60   990.0          440.16  24.0  25.56  180.0        537.0      3.80   
4  7.64   862.0          235.25  62.0  20.74   81.0        287.0      2.10   
6  8.13   788.0          304.92  18.0  20.69  132.0        372.0      2.40   

   Bin_Fluoride  
0             1  
2             1  
3             1  
4             1  
6             1

In [11]:
final_data = final_data.drop(['FLUORIDE'],axis=1)

In [12]:
final_data.shape

(14317, 8)

In [13]:
data = final_data

In [14]:
final_data = final_data.sample(frac=1)
final_data

PH      EC  TOT_ALKALINITY     CA      MG      NA  BICARBONATE  \
3485  8.32  1756.0      419.670000   62.0   42.62   230.0        451.0   
680   7.19   824.0      290.160000   64.0   38.98    20.0        354.0   
5158  8.50   650.0      250.163934   24.0   32.00   126.0        232.0   
1305  8.19   219.0       59.835910   28.0    8.54    13.0         73.0   
2844  6.84  1469.0      269.670000   88.0   41.44   140.0        329.0   
...    ...     ...             ...    ...     ...     ...          ...   
3536  7.60  1696.0      225.410000   60.0   32.90   206.0        275.0   
374   8.03  1190.0      245.081330   80.0    7.39   161.0        299.0   
2013  8.21   909.0      280.330000   48.0   23.16   115.0        342.0   
2822  7.70  7015.0      409.840000  240.0  267.74   830.0        500.0   
707   7.29  8500.0      300.000000  100.0  231.10  1410.0        366.0   

      Bin_Fluoride  
3485             1  
680              0  
5158             1  
1305             0  
2844             0  
...            ...  
3536             0  
374              1  
2013             0  
2822             0  
707              0  

[14317 rows x 8 columns]

In [15]:
x = final_data.drop(['Bin_Fluoride'],axis=1)
x

PH      EC  TOT_ALKALINITY     CA      MG      NA  BICARBONATE
3485  8.32  1756.0      419.670000   62.0   42.62   230.0        451.0
680   7.19   824.0      290.160000   64.0   38.98    20.0        354.0
5158  8.50   650.0      250.163934   24.0   32.00   126.0        232.0
1305  8.19   219.0       59.835910   28.0    8.54    13.0         73.0
2844  6.84  1469.0      269.670000   88.0   41.44   140.0        329.0
...    ...     ...             ...    ...     ...     ...          ...
3536  7.60  1696.0      225.410000   60.0   32.90   206.0        275.0
374   8.03  1190.0      245.081330   80.0    7.39   161.0        299.0
2013  8.21   909.0      280.330000   48.0   23.16   115.0        342.0
2822  7.70  7015.0      409.840000  240.0  267.74   830.0        500.0
707   7.29  8500.0      300.000000  100.0  231.10  1410.0        366.0

[14317 rows x 7 columns]

In [16]:
y = final_data[:]['Bin_Fluoride']
y

3485    1
680     0
5158    1
1305    0
2844    0
       ..
3536    0
374     1
2013    0
2822    0
707     0
Name: Bin_Fluoride, Length: 14317, dtype: int64

In [17]:
x_train,x_test=x[:10000],x[10000:]
x_train.shape

(10000, 7)

In [18]:
x_test.shape

(4317, 7)

In [19]:
y_train,y_test=y[:10000],y[10000:]
y_train.value_counts()

0    6741
1    3259
Name: Bin_Fluoride, dtype: int64

In [20]:
y_test.value_counts()

0    2944
1    1373
Name: Bin_Fluoride, dtype: int64

# ***Random Forest***

In [21]:
from sklearn.ensemble import RandomForestClassifier
clf_forest = RandomForestClassifier(max_depth=19, random_state=10)
clf_forest.fit(x_train,y_train)

RandomForestClassifier(max_depth=19, random_state=10)

In [22]:
y_test_predict_forest = clf_forest.predict(x_test[:][:])
y_test_predict_forest

array([0, 0, 0, ..., 0, 0, 0])

In [23]:
from sklearn.metrics import confusion_matrix

In [24]:
confusion_matrix(y_test,y_test_predict_forest)

array([[2612,  332],
       [ 800,  573]])

In [25]:
# [2629,  297], 
# [ 882,  509]]  10,10  
#  
# ([[2625,  301],
# [ 863,  528]])   12,10

# ([[2620,  306],
# [ 837,  554]])   14,10

In [26]:
# Modify data

In [27]:
data.head()

PH      EC  TOT_ALKALINITY    CA     MG     NA  BICARBONATE  Bin_Fluoride
0  7.83  2000.0          314.75  66.0  70.59  250.0        384.0             1
2  8.17   786.0          240.16  24.0  24.34  106.0        293.0             1
3  7.60   990.0          440.16  24.0  25.56  180.0        537.0             1
4  7.64   862.0          235.25  62.0  20.74   81.0        287.0             1
6  8.13   788.0          304.92  18.0  20.69  132.0        372.0             1

In [28]:
data['NA/CA'] = np.where(data['CA']!=0,data['NA']/data['CA'],0)
data.head()

PH      EC  TOT_ALKALINITY    CA     MG     NA  BICARBONATE  \
0  7.83  2000.0          314.75  66.0  70.59  250.0        384.0   
2  8.17   786.0          240.16  24.0  24.34  106.0        293.0   
3  7.60   990.0          440.16  24.0  25.56  180.0        537.0   
4  7.64   862.0          235.25  62.0  20.74   81.0        287.0   
6  8.13   788.0          304.92  18.0  20.69  132.0        372.0   

   Bin_Fluoride     NA/CA  
0             1  3.787879  
2             1  4.416667  
3             1  7.500000  
4             1  1.306452  
6             1  7.333333

In [29]:
data.count()

PH                14317
EC                14317
TOT_ALKALINITY    14317
CA                14317
MG                14317
NA                14317
BICARBONATE       14317
Bin_Fluoride      14317
NA/CA             14317
dtype: int64

In [30]:
data = data.dropna(axis=0)

In [31]:
data.count()

PH                14317
EC                14317
TOT_ALKALINITY    14317
CA                14317
MG                14317
NA                14317
BICARBONATE       14317
Bin_Fluoride      14317
NA/CA             14317
dtype: int64

In [32]:
data = data.astype("f")
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14317 entries, 0 to 4031
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   PH              14317 non-null  float32
 1   EC              14317 non-null  float32
 2   TOT_ALKALINITY  14317 non-null  float32
 3   CA              14317 non-null  float32
 4   MG              14317 non-null  float32
 5   NA              14317 non-null  float32
 6   BICARBONATE     14317 non-null  float32
 7   Bin_Fluoride    14317 non-null  float32
 8   NA/CA           14317 non-null  float32
dtypes: float32(9)
memory usage: 615.2 KB


In [33]:
data = data.sample(frac=1)
data.head()

PH      EC  TOT_ALKALINITY     CA          MG          NA  \
650   7.62  1825.0      569.669983   64.0  102.190002  173.000000   
1869  8.26   590.0      280.329987   20.0   24.340000  104.000000   
2178  7.63  1383.0      430.329987   64.0   32.900002  154.000000   
3831  6.90  1368.0        0.000000   84.0   58.329601   97.059998   
1627  7.30  1562.0        0.000000  112.0   80.203201   73.599998   

      BICARBONATE  Bin_Fluoride     NA/CA  
650    695.000000           0.0  2.703125  
1869   342.000000           1.0  5.200000  
2178   525.000000           0.0  2.406250  
3831   286.794006           0.0  1.155476  
1627   317.303986           1.0  0.657143

In [34]:
x = data.drop(['Bin_Fluoride','CA','NA'],axis=1)
x.head()

PH      EC  TOT_ALKALINITY          MG  BICARBONATE     NA/CA
650   7.62  1825.0      569.669983  102.190002   695.000000  2.703125
1869  8.26   590.0      280.329987   24.340000   342.000000  5.200000
2178  7.63  1383.0      430.329987   32.900002   525.000000  2.406250
3831  6.90  1368.0        0.000000   58.329601   286.794006  1.155476
1627  7.30  1562.0        0.000000   80.203201   317.303986  0.657143

In [35]:
y = data['Bin_Fluoride']
y.head()

650     0.0
1869    1.0
2178    0.0
3831    0.0
1627    1.0
Name: Bin_Fluoride, dtype: float32

In [36]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14317 entries, 650 to 898
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   PH              14317 non-null  float32
 1   EC              14317 non-null  float32
 2   TOT_ALKALINITY  14317 non-null  float32
 3   MG              14317 non-null  float32
 4   BICARBONATE     14317 non-null  float32
 5   NA/CA           14317 non-null  float32
dtypes: float32(6)
memory usage: 447.4 KB


In [37]:
x_train,x_test=x[:10000],x[10000:]
x_train.shape

(10000, 6)

In [38]:
x_test.shape

(4317, 6)

In [40]:
y_train,y_test=y[:10000],y[10000:]
y_train.shape

(10000,)

In [44]:
y_test.shape

(4317,)

## **Random forest**

In [41]:
x_train.head()

PH      EC  TOT_ALKALINITY          MG  BICARBONATE     NA/CA
650   7.62  1825.0      569.669983  102.190002   695.000000  2.703125
1869  8.26   590.0      280.329987   24.340000   342.000000  5.200000
2178  7.63  1383.0      430.329987   32.900002   525.000000  2.406250
3831  6.90  1368.0        0.000000   58.329601   286.794006  1.155476
1627  7.30  1562.0        0.000000   80.203201   317.303986  0.657143

In [51]:
# from sklearn.ensemble import RandomForestClassifier
new_forest = RandomForestClassifier(max_depth=14, random_state=10)
new_forest.fit(x_train,y_train)

RandomForestClassifier(max_depth=14, random_state=10)

In [52]:
y_test_predict_forest = new_forest.predict(x_test[:][:])
y_test_predict_forest

array([0., 1., 0., ..., 0., 0., 0.], dtype=float32)

In [53]:
confusion_matrix(y_test,y_test_predict_forest)

array([[2586,  335],
       [ 831,  565]])

In [ ]:
# [2629,  297], 
# [ 882,  509]]  10,10  
#  
# ([[2625,  301],
# [ 863,  528]])   12,10

# ([[2620,  306],
# [ 837,  554]])   14,10