In [1]:
import numpy as np
import pandas as pd

In [2]:
data_west = pd.read_excel("West_Bengal_filter.xlsx",sheet_name="Sheet1")
data_telangana = pd.read_excel("Telangana_filter.xlsx",sheet_name="Sheet1")
data_tamil = pd.read_excel("Tamil_Nadu_filter.xlsx",sheet_name="Sheet1")
data_rajasthan = pd.read_excel("Rajasthan_filter.xlsx",sheet_name="Sheet1")
data_andhra = pd.read_excel("Andhra_Pradesh_filter.xlsx",sheet_name="Sheet1")

In [3]:
final_data = pd.concat([data_andhra,data_rajasthan,data_tamil,data_telangana,data_west], axis=0)

In [4]:
# final_data.head()

In [5]:
# final_data.count()

In [6]:
final_data = final_data.dropna(axis=0)
final_data.count()

PH                14317
EC                14317
TOT_ALKALINITY    14317
CA                14317
MG                14317
NA                14317
BICARBONATE       14317
FLUORIDE          14317
dtype: int64

In [7]:
final_data = final_data.astype(float)
# final_data.info()

In [8]:
final_data.corr()

PH        EC  TOT_ALKALINITY        CA        MG  \
PH              1.000000  0.007638        0.159336 -0.258240 -0.072663   
EC              0.007638  1.000000        0.326843  0.588173  0.419715   
TOT_ALKALINITY  0.159336  0.326843        1.000000  0.066551  0.037629   
CA             -0.258240  0.588173        0.066551  1.000000  0.335212   
MG             -0.072663  0.419715        0.037629  0.335212  1.000000   
NA              0.111236  0.893397        0.365656  0.431942  0.316331   
BICARBONATE     0.004120  0.376564        0.858184  0.134535  0.158502   
FLUORIDE        0.104397  0.144962        0.207236 -0.021407  0.032624   

                      NA  BICARBONATE  FLUORIDE  
PH              0.111236     0.004120  0.104397  
EC              0.893397     0.376564  0.144962  
TOT_ALKALINITY  0.365656     0.858184  0.207236  
CA              0.431942     0.134535 -0.021407  
MG              0.316331     0.158502  0.032624  
NA              1.000000     0.383354  0.205203  
BICARBONATE     0.383354     1.000000  0.219009  
FLUORIDE        0.205203     0.219009  1.000000

In [9]:
final_data['Bin_Fluoride'] = np.where( final_data['FLUORIDE'] >= 1,1,0)
final_data['Bin_Fluoride'].value_counts()

0    9685
1    4632
Name: Bin_Fluoride, dtype: int64

In [10]:
# final_data.head()

In [11]:
final_data = final_data.drop(['FLUORIDE'],axis=1)

In [12]:
final_data.shape

(14317, 8)

In [13]:
data = final_data

In [14]:
final_data = final_data.sample(frac=1)
final_data

PH      EC  TOT_ALKALINITY     CA      MG      NA  BICARBONATE  \
4169  7.97  1100.0      319.672131    8.0   4.864  240.00       390.00   
1754  6.08   845.0       90.000000   46.0   3.645  101.71       109.80   
229   7.57  1900.0        6.098361   48.0  82.720  235.00         7.44   
711   7.30   925.0      314.750000   36.0  30.440  122.00       384.00   
582   7.10  1010.0      274.590164  129.0  24.000   42.00       335.00   
...    ...     ...             ...    ...     ...     ...          ...   
512   7.75   594.0       55.000000   26.0  29.160   49.31        67.10   
821   8.33  2000.0      270.000000   76.0  82.688  183.00       305.00   
2378  7.57  1130.0      300.000000  100.0  19.570  102.00       366.00   
622   7.69   639.0      290.160000   52.0  42.610   28.00       354.00   
2135  8.18   755.0      230.330000   40.0  51.110   35.00       281.00   

      Bin_Fluoride  
4169             1  
1754             0  
229              1  
711              1  
582              0  
...            ...  
512              0  
821              0  
2378             1  
622              0  
2135             0  

[14317 rows x 8 columns]

In [15]:
x = final_data.drop(['Bin_Fluoride'],axis=1)
x

PH      EC  TOT_ALKALINITY     CA      MG      NA  BICARBONATE
4169  7.97  1100.0      319.672131    8.0   4.864  240.00       390.00
1754  6.08   845.0       90.000000   46.0   3.645  101.71       109.80
229   7.57  1900.0        6.098361   48.0  82.720  235.00         7.44
711   7.30   925.0      314.750000   36.0  30.440  122.00       384.00
582   7.10  1010.0      274.590164  129.0  24.000   42.00       335.00
...    ...     ...             ...    ...     ...     ...          ...
512   7.75   594.0       55.000000   26.0  29.160   49.31        67.10
821   8.33  2000.0      270.000000   76.0  82.688  183.00       305.00
2378  7.57  1130.0      300.000000  100.0  19.570  102.00       366.00
622   7.69   639.0      290.160000   52.0  42.610   28.00       354.00
2135  8.18   755.0      230.330000   40.0  51.110   35.00       281.00

[14317 rows x 7 columns]

In [16]:
y = final_data[:]['Bin_Fluoride']
y

4169    1
1754    0
229     1
711     1
582     0
       ..
512     0
821     0
2378    1
622     0
2135    0
Name: Bin_Fluoride, Length: 14317, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.05, random_state=42)

In [18]:
# x_train,x_test=x[:10000],x[10000:]
x_train.shape

(13601, 7)

In [19]:
x_test.shape

(716, 7)

In [20]:
# y_train,y_test=y[:10000],y[10000:]
y_train.value_counts()

0    9188
1    4413
Name: Bin_Fluoride, dtype: int64

In [21]:
y_test.value_counts()

0    497
1    219
Name: Bin_Fluoride, dtype: int64

# ***Resample Test data***

In [22]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=12)
x_train,y_train = sm.fit_resample(x_train,y_train)

In [23]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18376 entries, 0 to 18375
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   PH              18376 non-null  float64
 1   EC              18376 non-null  float64
 2   TOT_ALKALINITY  18376 non-null  float64
 3   CA              18376 non-null  float64
 4   MG              18376 non-null  float64
 5   NA              18376 non-null  float64
 6   BICARBONATE     18376 non-null  float64
dtypes: float64(7)
memory usage: 1005.1 KB


In [24]:
y_train.info()

<class 'pandas.core.series.Series'>
RangeIndex: 18376 entries, 0 to 18375
Series name: Bin_Fluoride
Non-Null Count  Dtype
--------------  -----
18376 non-null  int64
dtypes: int64(1)
memory usage: 143.7 KB


In [25]:
y_train.value_counts()

0    9188
1    9188
Name: Bin_Fluoride, dtype: int64

# ***Random Forest***

In [26]:
from sklearn.ensemble import RandomForestClassifier
clf_forest = RandomForestClassifier(max_depth=19, random_state=10)
clf_forest.fit(x_train,y_train)

RandomForestClassifier(max_depth=19, random_state=10)

In [27]:
y_test_predict_forest = clf_forest.predict(x_test[:][:])
y_test_predict_forest

array([1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,

In [28]:
from sklearn.metrics import confusion_matrix

In [29]:
confusion_matrix(y_test,y_test_predict_forest)

array([[392, 105],
       [ 79, 140]])

In [30]:
# after resampling
# [[2226,  665],
# [ 603,  823]]       19,10


In [31]:
from sklearn.metrics import precision_score,recall_score
precision_score(y_test,y_test_predict_forest)

0.5714285714285714

In [32]:
recall_score(y_test,y_test_predict_forest)

0.639269406392694

In [33]:
from sklearn.metrics import f1_score
f1_score(y_test,y_test_predict_forest)

0.603448275862069

In [34]:
# without resampling
# [2629,  297], 
# [ 882,  509]]  10,10  
#  
# ([[2625,  301],
# [ 863,  528]])   12,10

# ([[2620,  306],
# [ 837,  554]])   14,10

# Modify data

In [35]:
# data.head()

In [36]:
# data['NA/CA'] = np.where(data['CA']!=0,data['NA']/data['CA'],0)
# data.head()

In [37]:
# data.count()

In [38]:
# data = data.dropna(axis=0)

In [39]:
# data.count()

In [40]:
# data = data.astype("f")
# data.info()

In [41]:
# data = data.sample(frac=1)
# data.head()

In [42]:
# x = data.drop(['Bin_Fluoride','CA','NA'],axis=1)
# x.head()

In [43]:
# y = data['Bin_Fluoride']
# y.head()

In [44]:
# x.info()

In [45]:
# x_train,x_test=x[:10000],x[10000:]
# x_train.shape

In [46]:
# x_test.shape

In [47]:
# y_train,y_test=y[:10000],y[10000:]
# y_train.shape

In [48]:
# y_test.shape

## Resample data

In [49]:
# y_train.value_counts()

In [50]:
# from imblearn.over_sampling import SMOTE
# sm = SMOTE(random_state=12)
# x_train,y_train = sm.fit_resample(x_train,y_train)

In [51]:
# y_train.value_counts()

## **Random forest**

In [52]:
# x_train.head()

In [ ]:
# from sklearn.ensemble import RandomForestClassifier
# new_forest = RandomForestClassifier(max_depth=19, random_state=10)
# new_forest.fit(x_train,y_train)

In [ ]:
# y_test_predict_forest = new_forest.predict(x_test[:][:])
# y_test_predict_forest

In [ ]:
# confusion_matrix(y_test,y_test_predict_forest)

In [ ]:
# array([[2110,  809],
#        [ 526,  872]])   14,10

# old
# array([[2269,  644],
    #    [ 604,  800]])

In [ ]:
# from sklearn.metrics import precision_score,recall_score
# precision_score(y_test,y_test_predict_forest)

In [ ]:
# recall_score(y_test,y_test_predict_forest)

In [ ]:
# from sklearn.metrics import f1_score
# f1_score(y_test,y_test_predict_forest)

## Logistic Regression

In [ ]:
# from sklearn.linear_model import LogisticRegression
# lgr = LogisticRegression(random_state = 10,solver = 'liblinear')
# lgr.fit(x_train,y_train)

In [ ]:
# y_test_predict_logistic = lgr.predict(x_test[:][:])
# y_test_predict_logistic

In [ ]:
# confusion_matrix(y_test,y_test_predict_logistic)

In [ ]:
# from sklearn.metrics import precision_score,recall_score
# precision_score(y_test,y_test_predict_logistic)

In [ ]:
# recall_score(y_test,y_test_predict_logistic)

In [ ]:
# from sklearn.metrics import f1_score
# f1_score(y_test,y_test_predict_logistic)

## ***KNN***

In [ ]:
# from sklearn.neighbors import KNeighborsClassifier
# neigh = KNeighborsClassifier(n_neighbors=9)
# neigh.fit(x_train,y_train)

In [ ]:
# y_test_predict_knn = lgr.predict(x_test[:][:])
# y_test_predict_knn

In [ ]:
# confusion_matrix(y_test,y_test_predict_knn)