In [1]:
import numpy as np
import pandas as pd

In [2]:
data_west = pd.read_excel("West_Bengal_filter.xlsx",sheet_name="Sheet1")
data_telangana = pd.read_excel("Telangana_filter.xlsx",sheet_name="Sheet1")
data_tamil = pd.read_excel("Tamil_Nadu_filter.xlsx",sheet_name="Sheet1")
data_rajasthan = pd.read_excel("Rajasthan_filter.xlsx",sheet_name="Sheet1")
data_andhra = pd.read_excel("Andhra_Pradesh_filter.xlsx",sheet_name="Sheet1")

In [3]:
final_data = pd.concat([data_andhra,data_rajasthan,data_tamil,data_telangana,data_west], axis=0)

In [4]:
# final_data.head()

In [5]:
# final_data.count()

In [6]:
final_data = final_data.dropna(axis=0)
final_data.count()

PH                14317
EC                14317
TOT_ALKALINITY    14317
CA                14317
MG                14317
NA                14317
BICARBONATE       14317
FLUORIDE          14317
dtype: int64

In [7]:
final_data = final_data.astype(float)
# final_data.info()

In [8]:
final_data.corr()

PH        EC  TOT_ALKALINITY        CA        MG  \
PH              1.000000  0.007638        0.159336 -0.258240 -0.072663   
EC              0.007638  1.000000        0.326843  0.588173  0.419715   
TOT_ALKALINITY  0.159336  0.326843        1.000000  0.066551  0.037629   
CA             -0.258240  0.588173        0.066551  1.000000  0.335212   
MG             -0.072663  0.419715        0.037629  0.335212  1.000000   
NA              0.111236  0.893397        0.365656  0.431942  0.316331   
BICARBONATE     0.004120  0.376564        0.858184  0.134535  0.158502   
FLUORIDE        0.104397  0.144962        0.207236 -0.021407  0.032624   

                      NA  BICARBONATE  FLUORIDE  
PH              0.111236     0.004120  0.104397  
EC              0.893397     0.376564  0.144962  
TOT_ALKALINITY  0.365656     0.858184  0.207236  
CA              0.431942     0.134535 -0.021407  
MG              0.316331     0.158502  0.032624  
NA              1.000000     0.383354  0.205203  
BICARBONATE     0.383354     1.000000  0.219009  
FLUORIDE        0.205203     0.219009  1.000000

In [9]:
final_data['Bin_Fluoride'] = np.where( final_data['FLUORIDE'] >= 1,1,0)
final_data['Bin_Fluoride'].value_counts()

0    9685
1    4632
Name: Bin_Fluoride, dtype: int64

In [10]:
# final_data.head()

In [11]:
final_data = final_data.drop(['FLUORIDE'],axis=1)

In [12]:
final_data.shape

(14317, 8)

In [13]:
data = final_data

In [14]:
final_data = final_data.sample(frac=1)
final_data

PH      EC  TOT_ALKALINITY     CA          MG      NA  BICARBONATE  \
323   7.17   895.0      335.245902  100.0   17.024000   75.00      409.000   
4809  8.00  2760.0      850.000000   20.0   34.048000  616.00     1037.000   
3146  7.92  2570.0      150.000000  200.0   72.900000  223.10      183.000   
1496  8.06   983.0      250.000000   78.0   20.760000   84.00      305.000   
810   8.06   877.0      354.801704  114.0   29.310000   37.00      433.000   
...    ...     ...             ...    ...         ...     ...          ...   
4614  8.50  2440.0      580.160000   17.0   31.020000  483.00      537.000   
2217  8.63   722.1      190.000000   10.0   87.378641   40.75      183.000   
2429  7.80  4470.0        0.000000  172.0  121.520000  579.60      469.854   
535   8.00   847.0      159.840000   56.0   38.970000   50.00      195.000   
3933  7.85  1600.0      450.000000   40.0   65.690000  198.00      549.000   

      Bin_Fluoride  
323              1  
4809             1  
3146             0  
1496             0  
810              0  
...            ...  
4614             1  
2217             0  
2429             1  
535              1  
3933             1  

[14317 rows x 8 columns]

In [15]:
x = final_data.drop(['Bin_Fluoride'],axis=1)
x

PH      EC  TOT_ALKALINITY     CA          MG      NA  BICARBONATE
323   7.17   895.0      335.245902  100.0   17.024000   75.00      409.000
4809  8.00  2760.0      850.000000   20.0   34.048000  616.00     1037.000
3146  7.92  2570.0      150.000000  200.0   72.900000  223.10      183.000
1496  8.06   983.0      250.000000   78.0   20.760000   84.00      305.000
810   8.06   877.0      354.801704  114.0   29.310000   37.00      433.000
...    ...     ...             ...    ...         ...     ...          ...
4614  8.50  2440.0      580.160000   17.0   31.020000  483.00      537.000
2217  8.63   722.1      190.000000   10.0   87.378641   40.75      183.000
2429  7.80  4470.0        0.000000  172.0  121.520000  579.60      469.854
535   8.00   847.0      159.840000   56.0   38.970000   50.00      195.000
3933  7.85  1600.0      450.000000   40.0   65.690000  198.00      549.000

[14317 rows x 7 columns]

In [16]:
y = final_data[:]['Bin_Fluoride']
y

323     1
4809    1
3146    0
1496    0
810     0
       ..
4614    1
2217    0
2429    1
535     1
3933    1
Name: Bin_Fluoride, Length: 14317, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [18]:
# x_train,x_test=x[:10000],x[10000:]
x_train.shape

(10021, 7)

In [19]:
x_test.shape

(4296, 7)

In [20]:
# y_train,y_test=y[:10000],y[10000:]
y_train.value_counts()

0    6761
1    3260
Name: Bin_Fluoride, dtype: int64

In [21]:
y_test.value_counts()

0    2924
1    1372
Name: Bin_Fluoride, dtype: int64

# ***Resample Test data***

In [22]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=12)
x_train,y_train = sm.fit_resample(x_train,y_train)

In [23]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13522 entries, 0 to 13521
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   PH              13522 non-null  float64
 1   EC              13522 non-null  float64
 2   TOT_ALKALINITY  13522 non-null  float64
 3   CA              13522 non-null  float64
 4   MG              13522 non-null  float64
 5   NA              13522 non-null  float64
 6   BICARBONATE     13522 non-null  float64
dtypes: float64(7)
memory usage: 739.6 KB


In [24]:
y_train.info()

<class 'pandas.core.series.Series'>
RangeIndex: 13522 entries, 0 to 13521
Series name: Bin_Fluoride
Non-Null Count  Dtype
--------------  -----
13522 non-null  int64
dtypes: int64(1)
memory usage: 105.8 KB


In [25]:
y_train.value_counts()

0    6761
1    6761
Name: Bin_Fluoride, dtype: int64

# ***Random Forest***

In [26]:
from sklearn.ensemble import RandomForestClassifier
clf_forest = RandomForestClassifier(max_depth=19, random_state=10)
clf_forest.fit(x_train,y_train)

RandomForestClassifier(max_depth=19, random_state=10)

In [27]:
y_test_predict_forest = clf_forest.predict(x_test[:][:])
y_test_predict_forest

array([1, 0, 0, ..., 0, 0, 0])

In [28]:
from sklearn.metrics import confusion_matrix

In [29]:
confusion_matrix(y_test,y_test_predict_forest)

array([[2305,  619],
       [ 609,  763]])

In [30]:
# after resampling
# [[2226,  665],
# [ 603,  823]]       19,10


In [31]:
from sklearn.metrics import precision_score,recall_score
precision_score(y_test,y_test_predict_forest)

0.5520984081041969

In [32]:
recall_score(y_test,y_test_predict_forest)

0.5561224489795918

In [33]:
from sklearn.metrics import f1_score
f1_score(y_test,y_test_predict_forest)

0.5541031227305738

In [34]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_test_predict_forest)

0.7141527001862198

In [35]:
# without resampling
# [2629,  297], 
# [ 882,  509]]  10,10  
#  
# ([[2625,  301],
# [ 863,  528]])   12,10

# ([[2620,  306],
# [ 837,  554]])   14,10

# Modify data

In [36]:
# data.head()

In [37]:
# data['NA/CA'] = np.where(data['CA']!=0,data['NA']/data['CA'],0)
# data.head()

In [38]:
# data.count()

In [39]:
# data = data.dropna(axis=0)

In [40]:
# data.count()

In [41]:
# data = data.astype("f")
# data.info()

In [42]:
# data = data.sample(frac=1)
# data.head()

In [43]:
# x = data.drop(['Bin_Fluoride','CA','NA'],axis=1)
# x.head()

In [44]:
# y = data['Bin_Fluoride']
# y.head()

In [45]:
# x.info()

In [46]:
# x_train,x_test=x[:10000],x[10000:]
# x_train.shape

In [47]:
# x_test.shape

In [48]:
# y_train,y_test=y[:10000],y[10000:]
# y_train.shape

In [49]:
# y_test.shape

## Resample data

In [50]:
# y_train.value_counts()

In [51]:
# from imblearn.over_sampling import SMOTE
# sm = SMOTE(random_state=12)
# x_train,y_train = sm.fit_resample(x_train,y_train)

In [52]:
# y_train.value_counts()

## **Random forest**

In [53]:
# x_train.head()

In [54]:
# from sklearn.ensemble import RandomForestClassifier
# new_forest = RandomForestClassifier(max_depth=19, random_state=10)
# new_forest.fit(x_train,y_train)

In [55]:
# y_test_predict_forest = new_forest.predict(x_test[:][:])
# y_test_predict_forest

In [56]:
# confusion_matrix(y_test,y_test_predict_forest)

In [57]:
# array([[2110,  809],
#        [ 526,  872]])   14,10

# old
# array([[2269,  644],
    #    [ 604,  800]])

In [58]:
# from sklearn.metrics import precision_score,recall_score
# precision_score(y_test,y_test_predict_forest)

In [59]:
# recall_score(y_test,y_test_predict_forest)

In [60]:
# from sklearn.metrics import f1_score
# f1_score(y_test,y_test_predict_forest)

## Logistic Regression

In [61]:
# from sklearn.linear_model import LogisticRegression
# lgr = LogisticRegression(random_state = 10,solver = 'liblinear')
# lgr.fit(x_train,y_train)

In [62]:
# y_test_predict_logistic = lgr.predict(x_test[:][:])
# y_test_predict_logistic

In [63]:
# confusion_matrix(y_test,y_test_predict_logistic)

In [64]:
# from sklearn.metrics import precision_score,recall_score
# precision_score(y_test,y_test_predict_logistic)

In [65]:
# recall_score(y_test,y_test_predict_logistic)

In [66]:
# from sklearn.metrics import f1_score
# f1_score(y_test,y_test_predict_logistic)

## ***KNN***

In [67]:
# from sklearn.neighbors import KNeighborsClassifier
# neigh = KNeighborsClassifier(n_neighbors=9)
# neigh.fit(x_train,y_train)

In [68]:
# y_test_predict_knn = lgr.predict(x_test[:][:])
# y_test_predict_knn

In [69]:
# confusion_matrix(y_test,y_test_predict_knn)