In [1]:
import numpy as np
import pandas as pd

In [2]:
data_west = pd.read_excel("West_Bengal_filter.xlsx",sheet_name="Sheet1")
data_telangana = pd.read_excel("Telangana_filter.xlsx",sheet_name="Sheet1")
data_tamil = pd.read_excel("Tamil_Nadu_filter.xlsx",sheet_name="Sheet1")
data_rajasthan = pd.read_excel("Rajasthan_filter.xlsx",sheet_name="Sheet1")
data_andhra = pd.read_excel("Andhra_Pradesh_filter.xlsx",sheet_name="Sheet1")

In [3]:
final_data = pd.concat([data_andhra,data_rajasthan,data_tamil,data_telangana,data_west], axis=0)

In [4]:
final_data.head()

PH      EC  TOT_ALKALINITY    CA     MG     NA  BICARBONATE  FLUORIDE
0  7.83  2000.0          314.75  66.0  70.59  250.0        384.0      2.20
1  7.61   674.0             NaN   NaN    NaN    NaN          NaN      1.20
2  8.17   786.0          240.16  24.0  24.34  106.0        293.0      3.83
3   7.6   990.0          440.16  24.0  25.56  180.0        537.0      3.80
4  7.64   862.0          235.25  62.0  20.74   81.0        287.0      2.10

In [5]:
final_data.count()

PH                20977
EC                21010
TOT_ALKALINITY    14653
CA                19681
MG                19679
NA                19575
BICARBONATE       19840
FLUORIDE          20391
dtype: int64

In [6]:
final_data = final_data.dropna(axis=0)
final_data.count()

PH                14317
EC                14317
TOT_ALKALINITY    14317
CA                14317
MG                14317
NA                14317
BICARBONATE       14317
FLUORIDE          14317
dtype: int64

In [7]:
final_data = final_data.astype(float)
final_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14317 entries, 0 to 4031
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   PH              14317 non-null  float64
 1   EC              14317 non-null  float64
 2   TOT_ALKALINITY  14317 non-null  float64
 3   CA              14317 non-null  float64
 4   MG              14317 non-null  float64
 5   NA              14317 non-null  float64
 6   BICARBONATE     14317 non-null  float64
 7   FLUORIDE        14317 non-null  float64
dtypes: float64(8)
memory usage: 1006.7 KB


In [8]:
final_data.corr()

PH        EC  TOT_ALKALINITY        CA        MG  \
PH              1.000000  0.007638        0.159336 -0.258240 -0.072663   
EC              0.007638  1.000000        0.326843  0.588173  0.419715   
TOT_ALKALINITY  0.159336  0.326843        1.000000  0.066551  0.037629   
CA             -0.258240  0.588173        0.066551  1.000000  0.335212   
MG             -0.072663  0.419715        0.037629  0.335212  1.000000   
NA              0.111236  0.893397        0.365656  0.431942  0.316331   
BICARBONATE     0.004120  0.376564        0.858184  0.134535  0.158502   
FLUORIDE        0.104397  0.144962        0.207236 -0.021407  0.032624   

                      NA  BICARBONATE  FLUORIDE  
PH              0.111236     0.004120  0.104397  
EC              0.893397     0.376564  0.144962  
TOT_ALKALINITY  0.365656     0.858184  0.207236  
CA              0.431942     0.134535 -0.021407  
MG              0.316331     0.158502  0.032624  
NA              1.000000     0.383354  0.205203  
BICARBONATE     0.383354     1.000000  0.219009  
FLUORIDE        0.205203     0.219009  1.000000

In [9]:
final_data['Bin_Fluoride'] = np.where( final_data['FLUORIDE'] >= 1,1,0)
final_data['Bin_Fluoride'].value_counts()

0    9685
1    4632
Name: Bin_Fluoride, dtype: int64

In [10]:
final_data.head()

PH      EC  TOT_ALKALINITY    CA     MG     NA  BICARBONATE  FLUORIDE  \
0  7.83  2000.0          314.75  66.0  70.59  250.0        384.0      2.20   
2  8.17   786.0          240.16  24.0  24.34  106.0        293.0      3.83   
3  7.60   990.0          440.16  24.0  25.56  180.0        537.0      3.80   
4  7.64   862.0          235.25  62.0  20.74   81.0        287.0      2.10   
6  8.13   788.0          304.92  18.0  20.69  132.0        372.0      2.40   

   Bin_Fluoride  
0             1  
2             1  
3             1  
4             1  
6             1

In [11]:
final_data = final_data.drop(['FLUORIDE'],axis=1)

In [12]:
final_data.shape

(14317, 8)

In [13]:
data = final_data

In [14]:
final_data = final_data.sample(frac=1)
final_data

PH      EC  TOT_ALKALINITY     CA        MG      NA  BICARBONATE  \
2939  8.14   582.0      205.000000   28.0   37.6650   30.69      250.100   
5031  7.90  1090.0      336.065574   70.0   35.3400  120.00      410.000   
1637  7.72  1000.0      269.670000   72.0   36.5600   84.00      329.000   
3853  7.20   998.0        0.000000   80.0   63.1904   41.17      408.834   
1618  7.90   474.0      165.000000   22.0   27.9450   96.00      201.300   
...    ...     ...             ...    ...       ...     ...          ...   
916   7.29   423.0      145.000000   26.0   24.3000   26.20      176.900   
2509  8.42  2000.0      420.330000   60.0   55.9900  200.00      464.000   
2782  7.36  2600.0      259.835390  124.0  113.2100  225.00      317.000   
2435  8.04   760.0      164.750000   42.0   16.5800   93.00      201.000   
3840  7.32   710.0      230.327869   48.0   46.2080   25.00      281.000   

      Bin_Fluoride  
2939             0  
5031             1  
1637             1  
3853             0  
1618             0  
...            ...  
916              0  
2509             1  
2782             0  
2435             0  
3840             0  

[14317 rows x 8 columns]

In [15]:
x = final_data.drop(['Bin_Fluoride'],axis=1)
x

PH      EC  TOT_ALKALINITY     CA        MG      NA  BICARBONATE
2939  8.14   582.0      205.000000   28.0   37.6650   30.69      250.100
5031  7.90  1090.0      336.065574   70.0   35.3400  120.00      410.000
1637  7.72  1000.0      269.670000   72.0   36.5600   84.00      329.000
3853  7.20   998.0        0.000000   80.0   63.1904   41.17      408.834
1618  7.90   474.0      165.000000   22.0   27.9450   96.00      201.300
...    ...     ...             ...    ...       ...     ...          ...
916   7.29   423.0      145.000000   26.0   24.3000   26.20      176.900
2509  8.42  2000.0      420.330000   60.0   55.9900  200.00      464.000
2782  7.36  2600.0      259.835390  124.0  113.2100  225.00      317.000
2435  8.04   760.0      164.750000   42.0   16.5800   93.00      201.000
3840  7.32   710.0      230.327869   48.0   46.2080   25.00      281.000

[14317 rows x 7 columns]

In [16]:
y = final_data[:]['Bin_Fluoride']
y

2939    0
5031    1
1637    1
3853    0
1618    0
       ..
916     0
2509    1
2782    0
2435    0
3840    0
Name: Bin_Fluoride, Length: 14317, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [18]:
# x_train,x_test=x[:10000],x[10000:]
x_train.shape

(10021, 7)

In [19]:
x_test.shape

(4296, 7)

In [20]:
# y_train,y_test=y[:10000],y[10000:]
y_train.value_counts()

0    6784
1    3237
Name: Bin_Fluoride, dtype: int64

In [21]:
y_test.value_counts()

0    2901
1    1395
Name: Bin_Fluoride, dtype: int64

# ***Resample Test data***

In [22]:
# from imblearn.over_sampling import SMOTE
# sm = SMOTE(random_state=12)
# x_train,y_train = sm.fit_resample(x_train,y_train)

In [23]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10021 entries, 1517 to 2436
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   PH              10021 non-null  float64
 1   EC              10021 non-null  float64
 2   TOT_ALKALINITY  10021 non-null  float64
 3   CA              10021 non-null  float64
 4   MG              10021 non-null  float64
 5   NA              10021 non-null  float64
 6   BICARBONATE     10021 non-null  float64
dtypes: float64(7)
memory usage: 626.3 KB


In [24]:
y_train.info()

<class 'pandas.core.series.Series'>
Int64Index: 10021 entries, 1517 to 2436
Series name: Bin_Fluoride
Non-Null Count  Dtype
--------------  -----
10021 non-null  int64
dtypes: int64(1)
memory usage: 156.6 KB


In [25]:
y_train.value_counts()

0    6784
1    3237
Name: Bin_Fluoride, dtype: int64

# ***Random Forest***

In [26]:
from sklearn.ensemble import RandomForestClassifier
clf_forest = RandomForestClassifier(max_depth=19, random_state=10)
clf_forest.fit(x_train,y_train)

RandomForestClassifier(max_depth=19, random_state=10)

In [27]:
y_test_predict_forest = clf_forest.predict(x_test[:][:])
y_test_predict_forest

array([0, 0, 1, ..., 1, 0, 0])

In [28]:
from sklearn.metrics import confusion_matrix

In [29]:
confusion_matrix(y_test,y_test_predict_forest)

array([[2610,  291],
       [ 858,  537]])

In [30]:
# after resampling
# [[2226,  665],
# [ 603,  823]]       19,10


In [31]:
# without resampling
# [2629,  297], 
# [ 882,  509]]  10,10  
#  
# ([[2625,  301],
# [ 863,  528]])   12,10

# ([[2620,  306],
# [ 837,  554]])   14,10

# Modify data

In [32]:
# data.head()

In [33]:
# data['NA/CA'] = np.where(data['CA']!=0,data['NA']/data['CA'],0)
# data.head()

In [34]:
# data.count()

In [35]:
# data = data.dropna(axis=0)

In [36]:
# data.count()

In [37]:
# data = data.astype("f")
# data.info()

In [38]:
# data = data.sample(frac=1)
# data.head()

In [39]:
# x = data.drop(['Bin_Fluoride','CA','NA'],axis=1)
# x.head()

In [40]:
# y = data['Bin_Fluoride']
# y.head()

In [41]:
# x.info()

In [42]:
# x_train,x_test=x[:10000],x[10000:]
# x_train.shape

In [43]:
# x_test.shape

In [44]:
# y_train,y_test=y[:10000],y[10000:]
# y_train.shape

In [45]:
# y_test.shape

## Resample data

In [46]:
# y_train.value_counts()

In [47]:
# from imblearn.over_sampling import SMOTE
# sm = SMOTE(random_state=12)
# x_train,y_train = sm.fit_resample(x_train,y_train)

In [48]:
# y_train.value_counts()

## **Random forest**

In [49]:
# x_train.head()

In [50]:
# from sklearn.ensemble import RandomForestClassifier
# new_forest = RandomForestClassifier(max_depth=19, random_state=10)
# new_forest.fit(x_train,y_train)

In [51]:
# y_test_predict_forest = new_forest.predict(x_test[:][:])
# y_test_predict_forest

In [52]:
# confusion_matrix(y_test,y_test_predict_forest)

In [53]:
# array([[2110,  809],
#        [ 526,  872]])   14,10

# old
# array([[2269,  644],
    #    [ 604,  800]])

In [54]:
# from sklearn.metrics import precision_score,recall_score
# precision_score(y_test,y_test_predict_forest)

In [55]:
# recall_score(y_test,y_test_predict_forest)

In [56]:
# from sklearn.metrics import f1_score
# f1_score(y_test,y_test_predict_forest)

## Logistic Regression

In [57]:
# from sklearn.linear_model import LogisticRegression
# lgr = LogisticRegression(random_state = 10,solver = 'liblinear')
# lgr.fit(x_train,y_train)

In [58]:
# y_test_predict_logistic = lgr.predict(x_test[:][:])
# y_test_predict_logistic

In [59]:
# confusion_matrix(y_test,y_test_predict_logistic)

In [60]:
# from sklearn.metrics import precision_score,recall_score
# precision_score(y_test,y_test_predict_logistic)

In [61]:
# recall_score(y_test,y_test_predict_logistic)

In [62]:
# from sklearn.metrics import f1_score
# f1_score(y_test,y_test_predict_logistic)

## ***KNN***

In [63]:
# from sklearn.neighbors import KNeighborsClassifier
# neigh = KNeighborsClassifier(n_neighbors=9)
# neigh.fit(x_train,y_train)

In [64]:
# y_test_predict_knn = lgr.predict(x_test[:][:])
# y_test_predict_knn

In [65]:
# confusion_matrix(y_test,y_test_predict_knn)