# **ML on Andhra Pradesh Data**

In [1]:
import pandas as pd
import numpy as np

In [2]:
# data = pd.read_excel("West_Bengal.xlsx",sheet_name="Sheet1")

In [3]:
# data.head()

In [4]:
# data = data.filter(['PH','EC','TOT_ALKALINITY','CA','MG','NA','BICARBONATE','FLUORIDE'], axis=1)

In [5]:
# data.to_excel("West_Bengal_filter.xlsx",sheet_name='Sheet1',index=False)

In [6]:
data = pd.read_excel("West_Bengal_filter.xlsx",sheet_name="Sheet1")

In [7]:
data.head()

PH      EC  TOT_ALKALINITY     CA     MG     NA  BICARBONATE  FLUORIDE
0  7.90   482.0           180.0   44.0  19.44   21.0        219.6      0.13
1  7.56   822.0           185.0   40.0   0.00  104.0        225.7      0.12
2  7.65   556.0           130.0   50.0  14.58   40.0        158.6      0.09
3  7.55  1675.0           430.0  146.0  29.16  165.0        524.6      0.18
4  7.93  1086.0           180.0   92.0  43.74   55.0        219.6      0.16

In [8]:
data = data.dropna(axis=0)
data.count()

PH                1573
EC                1573
TOT_ALKALINITY    1573
CA                1573
MG                1573
NA                1573
BICARBONATE       1573
FLUORIDE          1573
dtype: int64

In [9]:
data = data.astype(float)

In [10]:
data.corr()

PH        EC  TOT_ALKALINITY        CA        MG  \
PH              1.000000 -0.118032       -0.027802 -0.224156 -0.006188   
EC             -0.118032  1.000000        0.541955  0.527971  0.610683   
TOT_ALKALINITY -0.027802  0.541955        1.000000  0.336251  0.439616   
CA             -0.224156  0.527971        0.336251  1.000000  0.187834   
MG             -0.006188  0.610683        0.439616  0.187834  1.000000   
NA             -0.030114  0.829640        0.454791  0.264014  0.346161   
BICARBONATE    -0.117998  0.565184        0.975899  0.373001  0.431149   
FLUORIDE        0.292218 -0.002400        0.045109 -0.090231  0.198456   

                      NA  BICARBONATE  FLUORIDE  
PH             -0.030114    -0.117998  0.292218  
EC              0.829640     0.565184 -0.002400  
TOT_ALKALINITY  0.454791     0.975899  0.045109  
CA              0.264014     0.373001 -0.090231  
MG              0.346161     0.431149  0.198456  
NA              1.000000     0.460967 -0.012755  
BICARBONATE     0.460967     1.000000 -0.008643  
FLUORIDE       -0.012755    -0.008643  1.000000

In [11]:
data['Bin_Fluoride'] = np.where( data['FLUORIDE'] >= 1,1,0)
data['Bin_Fluoride'].value_counts()

0    1393
1     180
Name: Bin_Fluoride, dtype: int64

In [12]:
data.head()

PH      EC  TOT_ALKALINITY     CA     MG     NA  BICARBONATE  FLUORIDE  \
0  7.90   482.0           180.0   44.0  19.44   21.0        219.6      0.13   
1  7.56   822.0           185.0   40.0   0.00  104.0        225.7      0.12   
2  7.65   556.0           130.0   50.0  14.58   40.0        158.6      0.09   
3  7.55  1675.0           430.0  146.0  29.16  165.0        524.6      0.18   
4  7.93  1086.0           180.0   92.0  43.74   55.0        219.6      0.16   

   Bin_Fluoride  
0             0  
1             0  
2             0  
3             0  
4             0

In [13]:
data = data.drop(['FLUORIDE'],axis=1)

In [14]:
data.head()

PH      EC  TOT_ALKALINITY     CA     MG     NA  BICARBONATE  \
0  7.90   482.0           180.0   44.0  19.44   21.0        219.6   
1  7.56   822.0           185.0   40.0   0.00  104.0        225.7   
2  7.65   556.0           130.0   50.0  14.58   40.0        158.6   
3  7.55  1675.0           430.0  146.0  29.16  165.0        524.6   
4  7.93  1086.0           180.0   92.0  43.74   55.0        219.6   

   Bin_Fluoride  
0             0  
1             0  
2             0  
3             0  
4             0

In [15]:
data = data.sample(frac=1)
data

PH      EC  TOT_ALKALINITY    CA         MG      NA  BICARBONATE  \
1541  7.53   607.0           185.0  52.0  17.010000   42.00        225.7   
2768  8.31   900.3           140.0  48.0  38.834951   96.30         61.0   
761   8.48   140.0            45.0  22.0   1.215000    4.81         48.8   
1727  7.91   190.0            75.0  22.0   1.215000   11.00         91.5   
494   7.87   422.0           165.0  34.0  21.870000   21.06        201.3   
...    ...     ...             ...   ...        ...     ...          ...   
1007  8.14    86.0            20.0   8.0   3.645000    6.77         24.4   
1932  7.28   816.0           130.0  32.0   0.000000   91.82        158.6   
3554  7.68   881.0           155.0  50.0   6.075000  117.00        189.1   
87    7.91  3901.0           595.0  90.0  46.170000  605.00        725.9   
3752  7.71  1087.0           385.0  20.0  63.000000  100.00        469.7   

      Bin_Fluoride  
1541             0  
2768             0  
761              0  
1727             0  
494              0  
...            ...  
1007             0  
1932             0  
3554             0  
87               0  
3752             0  

[1573 rows x 8 columns]

In [16]:
x = data.drop(['Bin_Fluoride'],axis=1)
x

PH      EC  TOT_ALKALINITY    CA         MG      NA  BICARBONATE
1541  7.53   607.0           185.0  52.0  17.010000   42.00        225.7
2768  8.31   900.3           140.0  48.0  38.834951   96.30         61.0
761   8.48   140.0            45.0  22.0   1.215000    4.81         48.8
1727  7.91   190.0            75.0  22.0   1.215000   11.00         91.5
494   7.87   422.0           165.0  34.0  21.870000   21.06        201.3
...    ...     ...             ...   ...        ...     ...          ...
1007  8.14    86.0            20.0   8.0   3.645000    6.77         24.4
1932  7.28   816.0           130.0  32.0   0.000000   91.82        158.6
3554  7.68   881.0           155.0  50.0   6.075000  117.00        189.1
87    7.91  3901.0           595.0  90.0  46.170000  605.00        725.9
3752  7.71  1087.0           385.0  20.0  63.000000  100.00        469.7

[1573 rows x 7 columns]

In [17]:
y = data[:]['Bin_Fluoride']
y

1541    0
2768    0
761     0
1727    0
494     0
       ..
1007    0
1932    0
3554    0
87      0
3752    0
Name: Bin_Fluoride, Length: 1573, dtype: int64

In [18]:
x_train,x_test=x[:1100],x[1100:]
x_train.shape

(1100, 7)

In [19]:
x_test.shape

(473, 7)

In [20]:
y_train,y_test=y[:1100],y[1100:]
y_train.shape

(1100,)

In [21]:
y_test.shape

(473,)

# ***Logistic Regression***

In [22]:
from sklearn.linear_model import LogisticRegression
clf_lr = LogisticRegression()
clf_lr.fit(x_train,y_train)

LogisticRegression()

In [23]:
from sklearn.model_selection import cross_val_score
a = cross_val_score(clf_lr,x_train,y_train,cv=3,scoring="accuracy")

/home/elite/Documents/CODING/PYTHON/ML/water analysis/venv/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/elite/Documents/CODING/PYTHON/ML/water analysis/venv/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
   

In [24]:
a.mean()

0.8890898984033392

In [25]:
from sklearn.model_selection import cross_val_predict
y_train_predict = cross_val_predict(clf_lr,x_train,y_train,cv=3)

/home/elite/Documents/CODING/PYTHON/ML/water analysis/venv/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/elite/Documents/CODING/PYTHON/ML/water analysis/venv/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
   

In [26]:
y_train_predict

array([0, 0, 0, ..., 0, 0, 0])

In [27]:
type(y_test)

pandas.core.series.Series

## Confusion Matrix

In [28]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train,y_train_predict)

array([[963,   8],
       [114,  15]])

In [29]:
y_train.value_counts()

0    971
1    129
Name: Bin_Fluoride, dtype: int64

In [30]:
y_test.value_counts()

0    422
1     51
Name: Bin_Fluoride, dtype: int64

In [31]:
from sklearn.metrics import precision_score,recall_score
precision_score(y_train,y_train_predict)

0.6521739130434783

In [32]:
recall_score(y_train,y_train_predict)

0.11627906976744186

In [33]:
from sklearn.metrics import f1_score
f1_score(y_train,y_train_predict)

0.19736842105263158

In [34]:
y_test_predicted = clf_lr.predict(x_test[:][:])
y_test_predicted

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,

In [35]:
y_test.shape

(473,)

In [36]:
y_test_predicted.shape

(473,)

In [37]:
confusion_matrix(y_test,y_test_predicted)

array([[417,   5],
       [ 45,   6]])

# ***Random Forest***

In [82]:
from sklearn.ensemble import RandomForestClassifier
clf_forest = RandomForestClassifier(max_depth=10, random_state=10)
clf_forest.fit(x_train,y_train)

RandomForestClassifier(max_depth=10, random_state=10)

In [83]:
y_test_predict_forest = clf_forest.predict(x_test[:][:])
# y_test_predict_forest

In [84]:
confusion_matrix(y_test,y_test_predict_forest)

array([[414,   8],
       [ 38,  13]])